### PR TITLE
feat: provide a usage block in a module documentation

### PR DESCRIPTION
**Pull request by kitsonk**
Closes: #101

mod_ts_–_oak_–__v10_2_0_–_deno_land_x___Deno_Doc

This also updates some of the dependencies.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Looks great, could we get a button on the right to quickly copy the whole line?

**Comment by kitsonk** [comment]
> Looks great, could we get a button (icon) on the right to quickly copy the whole line?

So... that would require client side JavaScript, which I have been sort of trying to avoid, but I guess that is unavoidable to provide it.  Let me see what I can do.

**Comment by kitsonk** [comment]
Ok, wish granted @bartlomieju

mod_ts_–_oak_–__v10_2_0_–_deno_land_x___Deno_Doc

**Review by ry — APPROVED** [review]
LGTM!

**Pull request merged**
